# Generated by Django 4.1.2 on 2022-11-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T20',
            new_name='T_twenty',
        ),
    ]
