# Generated by Django 4.1.2 on 2022-11-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_test_ranking_allrounder'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='link',
            field=models.CharField(default='xyz', max_length=122),
            preserve_default=False,
        ),
    ]
