# Generated by Django 4.1.2 on 2022-11-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_match_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVENT',
        ),
        migrations.DeleteModel(
            name='MATCHE',
        ),
        migrations.DeleteModel(
            name='ONEDAY',
        ),
        migrations.DeleteModel(
            name='oneday_ranking_allrounder',
        ),
        migrations.DeleteModel(
            name='oneday_ranking_batsman',
        ),
        migrations.DeleteModel(
            name='oneday_ranking_bowler',
        ),
        migrations.DeleteModel(
            name='PLAYER',
        ),
        migrations.DeleteModel(
            name='t20_ranking_allrounder',
        ),
        migrations.DeleteModel(
            name='t20_ranking_batsman',
        ),
        migrations.DeleteModel(
            name='t20_ranking_bowler',
        ),
        migrations.DeleteModel(
            name='T_twenty',
        ),
        migrations.DeleteModel(
            name='TEST',
        ),
        migrations.DeleteModel(
            name='test_ranking_allrounder',
        ),
        migrations.DeleteModel(
            name='test_ranking_batsman',
        ),
        migrations.DeleteModel(
            name='test_ranking_bowler',
        ),
    ]
